### ISSUE TITLE
Autolayout does not work correctly for groups of nodes. Where did I go wrong?

### ISSUE THREAD

**Issue by anton12042001** [tbo47/dagre-es#24]
Autolayout does not work correctly for groups of nodes. I made an autolayout for nodes, but when I use groups, the position for this group is not set correctly. 
I put all the nodes in the graph, and the nodes that contain the parent group I used in the setParent method.
![image](https://github.com/tbo47/dagre-es/assets/98453976/8ede77a9-8f10-4c3c-8cb7-e8988daa2407)
After calling the Laout function, the positions are given out, but not quite the correct positions are given to the groups of nodes. What could be the problem?
![image](https://github.com/tbo47/dagre-es/assets/98453976/aa08aac8-d5cb-4b58-8453-8ab37ae4d2a3)

**Comment by aloisklink** [comment]
Hi @anton12042001, are you having the same issue with https://github.com/dagrejs/dagre?

This project is mainly just the https://github.com/dagrejs/dagre library with some slight modifications to be an [ECMAScript module](https://nodejs.org/api/esm.html#modules-ecmascript-modules).

If your issue is also with https://github.com/dagrejs/dagre, you might have better luck reporting the issue in that project :smile:

**Comment by anton12042001** [comment]
thanks, figured it out❤️

**Comment by aloisklink** [comment]
> thanks, figured it out :heart: 

Awesome! Do you know if it was a bug on the `dagre-es` end or on your end?

Either way, it might be worth commenting your solution here, since somebody might have the same problem as you and find this same issue!

Obligatory xkcd: https://xkcd.com/979/
