### ISSUE TITLE
Can you provide the min.js file?

### ISSUE THREAD

**Issue by Gahon1995** [tbo47/dagre-es#43]

**Comment by aloisklink** [comment]
Hi @Gahon1995,

I don't think it would be easy to create a bundle of this library, since there are so many entry-points.

E.g., users do: `import { layout as dagreLayout } from 'dagre-d3-es/src/dagre/index.js';`

If you do need a bundle (I assume this is what you mean by a `.min.js` file), I'd recommend using the bundles from the upstream projects (I believe they're in UMD format, so they should work both as an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) and [CommonJS](https://nodejs.org/docs/latest/api/modules.html)).

- https://github.com/dagrejs/dagre/tree/master/dist
- https://github.com/dagrejs/graphlib/tree/master/dist
- https://github.com/dagrejs/dagre-d3/tree/master/dist

Alternatively, you can setup Vite/[ESBuild](https://github.com/evanw/esbuild) to automatically make your own bundle!

---

I'm going to close this issue as not planned. But @tbo47 (or anybody else) feel free to re-open this issue if you disagree.

**Comment by tbo47** [comment]
Hi @Gahon1995 
I created an exemple here https://tbo47.github.io/dagre-d3-esm_example1/

Note this line:
```javascript
import * as dagreD3 from "https://tbo47.github.io/dagre-d3-es.7.0.11.js";
```

**Comment by tbo47** [comment]
I also created this example https://jsfiddle.net/tbo47/fm9ovqeb/
